---
name: Sync Fork

on:
  schedule:
    # every hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          git pull
          git switch master
          git remote add -f upstream https://github.com/microsoft/winget-pkgs.git
          git rebase upstream/master
          git push origin master
